name: leolm_simple_server
services:
  app1:
    image: leolm-simple-server:v3
    build: 
      context: ../
      dockerfile: ./docker/Dockerfile    
    environment:
      - APP_NAME=APP1
    ports:
      - 8081:8080
    networks:
      - appsNetwork
  app2:
    image: leolm-simple-server:v3
    build: 
      context: ../
      dockerfile: ./docker/Dockerfile  
    environment:
      - APP_NAME=APP2
    ports:
      - 8082:8080
    networks:
      - appsNetwork
  app3:
    image: leolm-simple-server:v3
    build: 
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      - APP_NAME=APP3
    ports:
      - 8083:8080
    networks:
      - appsNetwork
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./data/nginx.conf:/etc/nginx/nginx.conf  
    ports:
      - 8085:8085
    networks:
      - appsNetwork
    depends_on:
      - app1
      - app2
      - app3
networks:
  appsNetwork: {}
