version: '3.9'
services:
  app1:
    image: leolm-simple-server:v2
    build: 
      context: ../
      dockerfile: ./docker/Dockerfile    
    environment:
      - APP_NAME=APP1
    ports:
      - 8081:8080
    networks:
      - appsNetwork
  app2:
    image: leolm-simple-server:v2
    build: 
      context: ../
      dockerfile: ./docker/Dockerfile  
    environment:
      - APP_NAME=APP2
    ports:
      - 8082:8080
    networks:
      - appsNetwork
  app3:
    image: leolm-simple-server:v2
    build: 
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      - APP_NAME=APP3
    ports:
      - 8083:8080
    networks:
      - appsNetwork
networks:
  appsNetwork: {}
